version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  reviewers:
  - iphoting
  assignees:
  - iphoting
  versioning-strategy: auto
